In [33]:
# Import libraries
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report





In [34]:
# Load Iris dataset
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target

# Check for missing values and fill using mean (if any)
df.fillna(df.mean(numeric_only=True), inplace=True)

In [35]:
# Apply Min-Max Scaling
scaler = MinMaxScaler()
feature_cols = iris.feature_names
df[feature_cols] = scaler.fit_transform(df[feature_cols])


In [36]:
# Features and target
X = df[feature_cols]
y = df['target']


In [37]:
# Define train-test split ratios
split_ratios = {
    "50:50": 0.50,
    "60:40": 0.40,
    "70:30": 0.30,
    "80:20": 0.20
}


In [38]:
# Define K values to test
k_values = [1, 3, 5, 7, 9, 11, 13, 15]

# Store results
results = []

In [39]:

# Loop over each split ratio
for ratio_name, test_size in split_ratios.items():
    # Split the dataset
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=42
    )

    print(f"\n=== Split Ratio: {ratio_name} ===")
    print(f"Training samples: {len(X_train)}, Testing samples: {len(X_test)}")

    # Loop over each k value
    for k in k_values:
        # Create and train KNN classifier
        classifier = KNeighborsClassifier(n_neighbors=k)
        classifier.fit(X_train, y_train)

        # Predict test set
        y_pred = classifier.predict(X_test)

        # Evaluation metrics
        acc = accuracy_score(y_test, y_pred)
        cm = confusion_matrix(y_test, y_pred)
        report = classification_report(y_test, y_pred, target_names=iris.target_names, zero_division=0)

        # Print metrics
        print(f"\nK = {k}")
        print(f"Accuracy: {acc:.4f}")
        print("Confusion Matrix:")
        print(cm)
        print("Classification Report:")
        print(report)

        # Store results for comparison
        results.append({
            'Split Ratio': ratio_name,
            'K': k,
            'Accuracy': acc,
            'Confusion Matrix': cm,
            'Classification Report': report
        })
# Identify the best split ratio and K based on highest accuracy
best_result = max(results, key=lambda x: x['Accuracy'])
print("\n=== Best Result ===")
print(f"Split Ratio: {best_result['Split Ratio']}")
print(f"Optimal K: {best_result['K']}")
print(f"Accuracy: {best_result['Accuracy']:.4f}")
print("Confusion Matrix:")
print(best_result['Confusion Matrix'])
print("Classification Report:")
print(best_result['Classification Report'])




=== Split Ratio: 50:50 ===
Training samples: 75, Testing samples: 75

K = 1
Accuracy: 0.9867
Confusion Matrix:
[[29  0  0]
 [ 0 23  0]
 [ 0  1 22]]
Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        29
  versicolor       0.96      1.00      0.98        23
   virginica       1.00      0.96      0.98        23

    accuracy                           0.99        75
   macro avg       0.99      0.99      0.99        75
weighted avg       0.99      0.99      0.99        75


K = 3
Accuracy: 0.9867
Confusion Matrix:
[[29  0  0]
 [ 0 23  0]
 [ 0  1 22]]
Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        29
  versicolor       0.96      1.00      0.98        23
   virginica       1.00      0.96      0.98        23

    accuracy                           0.99        75
   macro avg       0.99      0.99      0.99        75
weighted avg       