#ndarray Manipulation -1

In [3]:
import numpy as np
arr=np.random.randint(1,100, size=(10,5)) #
print(arr)

[[19 99 18 50 71]
 [21 18 29 10 73]
 [52  6 21 92 41]
 [36 75 58 50 40]
 [60 44 89 13 31]
 [19 77 82 26 66]
 [43 40 70  6  3]
 [13 19 98 85 99]
 [80 44 17 95 41]
 [66 24 50 79 84]]


In [4]:
arr.shape

(10, 5)

In [5]:
b=arr.reshape(5,10).copy()
print(b)
b.shape

[[19 99 18 50 71 21 18 29 10 73]
 [52  6 21 92 41 36 75 58 50 40]
 [60 44 89 13 31 19 77 82 26 66]
 [43 40 70  6  3 13 19 98 85 99]
 [80 44 17 95 41 66 24 50 79 84]]


(5, 10)

In [6]:

b.ndim

2

In [7]:
flatten=b.flatten() #raw
print(flatten)
flatten.ndim

[19 99 18 50 71 21 18 29 10 73 52  6 21 92 41 36 75 58 50 40 60 44 89 13
 31 19 77 82 26 66 43 40 70  6  3 13 19 98 85 99 80 44 17 95 41 66 24 50
 79 84]


1

In [8]:
column_falttening=np.ravel(b,order='F')
print(column_falttening)

[19 52 60 43 80 99  6 44 40 44 18 21 89 70 17 50 92 13  6 95 71 41 31  3
 41 21 36 19 13 66 18 75 77 19 24 29 58 82 98 50 10 50 26 85 79 73 40 66
 99 84]


In [9]:
a=np.random.randint(1,10,size=(2,3))
b=np.random.randint(1,10,size=(2,3))
print(a )
print(b)


[[4 5 5]
 [8 1 8]]
[[1 9 1]
 [6 1 7]]


concatenate

In [10]:
con=np.concatenate((a,b),axis=0) #row wise
print(con)

col=np.concatenate((a,b),axis=1) #column wise
print(col)

[[4 5 5]
 [8 1 8]
 [1 9 1]
 [6 1 7]]
[[4 5 5 1 9 1]
 [8 1 8 6 1 7]]


In [11]:
mat=np.array([
    [10,20,30],
    [30,40,50]
])

transpose=mat.T
print(transpose)

[[10 30]
 [20 40]
 [30 50]]


In [12]:
#array split
a=np.random.randint(1,10,size=(10,))
print(a)
splitted_arr=np.array_split(a,3)
print(splitted_arr)

#equal split
#splitted_arr=split(a,3)

[7 1 7 9 5 6 3 6 2 3]
[array([7, 1, 7, 9]), array([5, 6, 3]), array([6, 2, 3])]


ndarray Arithmetic Operators and Mathematical function

In [13]:
x=np.array([10,20,30,40,100])
y=np.array([2,3,4,5,50])
add=x+y
print(add)
sub=x-y
print(sub)
mul=x*y
print(mul)
div=x/y
print(div)
mud=x%y
print(mud)

[ 12  23  34  45 150]
[ 8 17 26 35 50]
[  20   60  120  200 5000]
[5.         6.66666667 7.5        8.         2.        ]
[0 2 2 0 0]


In [14]:
#mathmestical function

#trigonometry
#sin cos tan takes values in radian
sin_val=np.sin(x)
print(sin_val)
#degre
deg_con=np.rad2deg(x)
print(deg_con)
#def2red

[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.50636564]
[ 572.95779513 1145.91559026 1718.87338539 2291.83118052 5729.57795131]


In [15]:
#log
base_10_log_val=np.log10(x)
print(base_10_log_val)

two_time_div=np.log2(x)
print(two_time_div)

sqrt=np.sqrt(x)
print(sqrt)

[1.         1.30103    1.47712125 1.60205999 2.        ]
[3.32192809 4.32192809 4.9068906  5.32192809 6.64385619]
[ 3.16227766  4.47213595  5.47722558  6.32455532 10.        ]


In [16]:
#diff
s=np.sum(x)
print(s)
cumul=np.cumsum(x)
print(cumul)

200
[ 10  30  60 100 200]


#Numpy Broadcasting

In [17]:
x=np.array([10,8,16,100])
result=x**2
print(result)

[  100    64   256 10000]


In [18]:
#column size and vector size same
mat=np.array([
    [10,20,30],
    [30,40,50]
])
result=mat**2

vector=np.array([1,2,3])
result=mat+vector
print(result)


[[11 22 33]
 [31 42 53]]


#Numpy Logical Functions

In [19]:
#comparison - <,>,<=,>=,==,!=
x=np.array([10,8,16,100])
y=np.array([2,3,4,5])

grater_than=x>y
print(grater_than)

less_than=x<y
print(less_than)

equal_to=x==y
print(equal_to)

not_equal_to=x!=y
print(not_equal_to)


#all() -> all true check
#any() -> any true check

print(np.all(grater_than))

print(np.any(equal_to))

[ True  True  True  True]
[False False False False]
[False False False False]
[ True  True  True  True]
True
False


ndarray Sorting


In [20]:
#inplace
x=np.array([10, 8,16,100])
print(x)
z=x.copy()
z.sort()
print(z)

[ 10   8  16 100]
[  8  10  16 100]


In [21]:
#copy
print(x)
sort_arr=np.sort(x)
print(sort_arr)
print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [22]:
mat=np.array([
    [10,3,5],
    [8,4,9]
])

#horizon axis=1
hor_sor=np.sort(mat,axis=1)
print(hor_sor)

#vertical axis=0

var_sort=np.sort(mat,axis=0)
print(var_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


searching

In [23]:
print(x)

[ 10   8  16 100]


In [24]:
#np.where (condition ,x,y) if true x,otherwise replace with y
index=np.where(x==8)  #return index
print(index)

arr=np.where(x>8,x,0) #return array
print(arr)

(array([1]),)
[ 10   0  16 100]


In [25]:
print(mat)

[[10  3  5]
 [ 8  4  9]]


In [26]:
index=np.where(mat>8)
print(index)
arr=np.where(mat>8,mat,0) #return array
print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [27]:
print(x)
max_val=np.argmax(x)
min_val=np.argmin(x)
print(max_val)
print(min_val)

[ 10   8  16 100]
3
1


##*counting

In [28]:
a=np.random.randint(1,100,size=(100,))
print(a)

[27 55 69  6 49 85 83  7 92 35 59 98 57 47 28  9 16 24 48 94 45 34 51 30
 84 10 79 61 67 10 75 52 14 93  7 33 88 26 51 26 76 24 23 97 22 63  1 99
 98 31 60 73 38 10 10 67 56 50  3 84 70 27 95 68 96 21  9 82 48 84 10 54
 47 10 61 37 35 14 51 10 77 25 69  2 53 65 48 22 47 73 19 77 71 81 68 97
  3 84 53 45]


In [29]:
val_greet_than_60=np.count_nonzero(a>10)
print(val_greet_than_60)

84


In [30]:
unique_val=np.unique(a)
print(unique_val)


[ 1  2  3  6  7  9 10 14 16 19 21 22 23 24 25 26 27 28 30 31 33 34 35 37
 38 45 47 48 49 50 51 52 53 54 55 56 57 59 60 61 63 65 67 68 69 70 71 73
 75 76 77 79 81 82 83 84 85 88 92 93 94 95 96 97 98 99]


In [38]:
unique_val,count=np.unique(a,return_counts=True)
print(unique_val)
print(count)

[ 1  2  3  6  7  9 10 14 16 19 21 22 23 24 25 26 27 28 30 31 33 34 35 37
 38 45 47 48 49 50 51 52 53 54 55 56 57 59 60 61 63 65 67 68 69 70 71 73
 75 76 77 79 81 82 83 84 85 88 92 93 94 95 96 97 98 99]
[1 1 2 1 2 2 7 2 1 1 1 2 1 2 1 2 2 1 1 1 1 1 2 1 1 2 3 3 1 1 3 1 2 1 1 1 1
 1 1 2 1 1 2 2 2 1 1 2 1 1 2 1 1 1 1 4 1 1 1 1 1 1 1 2 2 1]


##Statistical function


In [43]:
data = np.genfromtxt('./sample_data/student_scores.csv', delimiter=',',skip_header=1)
print(data)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [49]:
mat_mark=data[::,:1]
print(mat_mark.T)
max_mat=np.max(mat_mark)
print(max_mat)

min_mat=np.min(mat_mark)
print(min_mat)

mean_mat=np.mean(mat_mark)
print(mean_mat)

median_mat=np.median(mat_mark)
print(median_mat)

std_mat=np.std(mat_mark)
print(std_mat)

[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
95.0
45.0
73.15
73.5
13.788672887555204


##Linear Algebra with NumPy


In [52]:
A=np.array([
    [1,2,3],
    [3,4,6]
])
B=np.array([

    [7,8],
    [9,10],
    [11,12]
])

dot_product=np.dot(A,B)
print(dot_product)

print(np.trace(B))

#

[[ 58  64]
 [123 136]]
17


In [57]:
sq_mat=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

det_of_sq=np.linalg.det(sq_mat)
print(det_of_sq)

0.0


In [59]:
rank_sq=np.linalg.matrix_rank(sq_mat)
print(rank_sq)

2
