#ndarray and its attributes

In [38]:
arr=[1,2,3,4,5]
print(arr*5)
arr=[x*5 for x in arr]
print(arr)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[5, 10, 15, 20, 25]


In [39]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr1=arr1*5
print(arr1)

[ 5 10 15 20 25]


NdArray

In [40]:
import numpy as np
#1d array

arr1=np.array([1,2,3,4,5])
print(type(arr1))
print(arr1.ndim)

#2d array
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2.ndim)

#3D ARRAY
arr3=np.array([
    [[1,2,3,4],[5,6,7,8]],
    [[11,12,13,14],[15,16,17,18]],
    [[1,2,3,4],[5,6,7,8]],
])
print(arr3.ndim)

<class 'numpy.ndarray'>
1
2
3


Array attribute

In [41]:
#dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
#size
print(arr1.size)
print(arr2.size)
print(arr3.size)
#dtypea
print(arr1.dtype)
print(arr2.dtype)
print(arr2.dtype)


1
2
3
(5,)
(2, 4)
(3, 2, 4)
5
8
24
int64
int64
int64


Ndarray Data Type

In [42]:
arr=np.array([1,2,3])

print(arr.dtype)
#upcasted to float
arr=np.array([1.4,5.7])
print(arr.dtype)

int64
float64


In [43]:
arr=np

In [44]:
#upcasted to string
arr=np.array([1.4,5.7,1,2,"3"])
print(arr.dtype)

<U32


selecting a data type for an array

In [45]:
import numpy as np
arr=np.array([1,2,3],dtype=np.int8)
print(arr.dtype)


int8


In [46]:
import numpy as np
arr=np.array([1,2,3])
arr=arr.astype(np.int16)
print(arr.dtype)



arr=arr.astype(np.int32)
print(arr.dtype)
#error
# arr=np.array([1.4,5.7,1,2,"Hello"],dtype=np.float64)

# arr=np.array([1.4,True,[11,22],1,2,"Hello"])

int16
int32


list

In [47]:
lst=[10.8,30,40,50,60]
arr=np.array(lst)
print(arr.dtype)
print(type(arr))

float64
<class 'numpy.ndarray'>


ndarray creation from existing data

In [48]:
import numpy as np
lst=[10,20,30,40,40.5]
arr=np.array(lst,dtype=np.int32)
# print(arr)
# print(arr.dtype)


mixed_lst=[10,True,'hello',20.4]
arr=np.array(mixed_lst)
print(arr)
print(arr.dtype)

['10' 'True' 'hello' '20.4']
<U32


In [49]:
matrix=[[1,2,3,4],[5,6,7,8]]
arr=np.array(matrix)
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
int64
<class 'numpy.ndarray'>
2
(2, 4)


In [50]:
#tuple
tpl=(10,20,30,40)
arr=np.array(tpl,dtype=np.int32)

print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)

int32
<class 'numpy.ndarray'>
1
(4,)


In [51]:

set1={1, 2, 3, 4}
arr=np.array(list(set1))

arr=arr.astype(np.int16)
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)

[1 2 3 4]
int16
<class 'numpy.ndarray'>
1
(4,)


In [52]:
#dic
dc={'a':10,'b':20,'c':30}
print(type(dc))
keys=dc.keys()
values=dc.values()
items=dc.items()
print(items)

<class 'dict'>
dict_items([('a', 10), ('b', 20), ('c', 30)])


In [53]:
#keys to ndarray

arr=np.array(list(keys))

# arr=arr.astype(np.int16)
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)

['a' 'b' 'c']
<U1
<class 'numpy.ndarray'>
1
(3,)


In [54]:
#values to ndarray

arr=np.array(list(values))

arr=arr.astype(np.int16)
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)

[10 20 30]
int16
<class 'numpy.ndarray'>
1
(3,)


In [55]:
#values to ndarray

arr=np.array(list(items))

# arr=arr.astype(np.int16)
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<U21
<class 'numpy.ndarray'>
2
(3, 2)


#creating ndarray from scratch



In [56]:
#np.zeros
arr=np.zeros((3,3),dtype=np.int32)
# print(arr)
# print(arr.dtype)
# print(type(arr))
# print(arr.ndim)
# print(arr.shape)


arr=np.zeros_like(arr3) #arr3 samme
print(arr)
print(arr.shape)

[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]
(3, 2, 4)


In [57]:
#np.one
arr=np.ones((3,3),dtype=np.int32)
# print(arr)
# print(arr.dtype)
# print(type(arr))
# print(arr.ndim)
# print(arr.shape)


arr=np.ones_like(arr3) #arr3 samme
print(arr)
print(arr.shape)

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]
(3, 2, 4)


In [58]:
#np.empty
arr=np.empty((4,3),dtype=np.int32) #ramdom value
# print(arr)
# print(arr.dtype)
# print(type(arr))
# print(arr.ndim)
# print(arr.shape)

arr=np.empty_like(arr3)
print(arr)

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


In [59]:
#np.full
arr=np.full((4,3),10) #value select
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)

[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]
int64
<class 'numpy.ndarray'>
2
(4, 3)


In [60]:
#np.full
arr=np.full((4,3),np.inf)
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]
float64
<class 'numpy.ndarray'>
2
(4, 3)


In [61]:
#np.full
arr=np.full((4,3),np.inf)

arr=np.full_like(arr3,np.inf)
print(arr)
print(arr.shape)

[[[-9223372036854775808 -9223372036854775808 -9223372036854775808
   -9223372036854775808]
  [-9223372036854775808 -9223372036854775808 -9223372036854775808
   -9223372036854775808]]

 [[-9223372036854775808 -9223372036854775808 -9223372036854775808
   -9223372036854775808]
  [-9223372036854775808 -9223372036854775808 -9223372036854775808
   -9223372036854775808]]

 [[-9223372036854775808 -9223372036854775808 -9223372036854775808
   -9223372036854775808]
  [-9223372036854775808 -9223372036854775808 -9223372036854775808
   -9223372036854775808]]]
(3, 2, 4)


In [62]:
#np.full

arr=np.full_like(arr3,np.inf,dtype=np.float64)
print(arr)
print(arr.shape)

[[[inf inf inf inf]
  [inf inf inf inf]]

 [[inf inf inf inf]
  [inf inf inf inf]]

 [[inf inf inf inf]
  [inf inf inf inf]]]
(3, 2, 4)


ndarray generation with random values

In [63]:
#np.random.rand(shape)
arr=np.random.rand(2,3) #0 t0 1
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)


[[0.17887622 0.21215445 0.08251987]
 [0.16297084 0.14477626 0.75025983]]
float64
<class 'numpy.ndarray'>
2
(2, 3)
6


In [64]:
#np.random.rand(start,end,shape)
arr=np.random.randint(1,10, (2,3)) #0 t0 10
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)


[[8 4 5]
 [6 9 9]]
int64
<class 'numpy.ndarray'>
2
(2, 3)
6


In [65]:
#np.random.uniform(start,end,shape)
arr=np.random.uniform(50,100, (3,4)) #
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)


[[73.25625819 54.34765222 58.38686476 82.5621506 ]
 [70.40942575 56.85806435 99.0840518  59.45095288]
 [81.13156278 86.26912112 95.584777   99.86466378]]
float64
<class 'numpy.ndarray'>
2
(3, 4)
12


In [66]:
#np.arange(first,end,step)
arr=np.arange(1,10,1).reshape(3,3)
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64
<class 'numpy.ndarray'>
2
(3, 3)
9


ndarray creation from range

In [67]:
#np.range(first,end,step)
arr=np.arange(1,10,1).reshape(3,3)
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64
<class 'numpy.ndarray'>
2
(3, 3)
9


In [68]:
#np.range(first,end,step)
arr=np.arange(1,10,1)
mat=arr.reshape(3,3)
print(mat)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64
<class 'numpy.ndarray'>
1
(9,)
9


In [69]:
#np.linspace(start,end(include),koita)

arr=np.linspace(1,10,15)
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)


[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]
float64
<class 'numpy.ndarray'>
1
(15,)
15


In [70]:
#np.longspace(start,end,koita) power

arr=np.logspace(1,4,5,base=2)
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)

[ 2.          3.36358566  5.65685425  9.51365692 16.        ]
float64
<class 'numpy.ndarray'>
1
(5,)
5


#creating diagonal and identity matrix

In [71]:
#creating mateix for liner algebra
diagonal_matrix=np.diag([2,3,4])
print(diagonal_matrix)

[[2 0 0]
 [0 3 0]
 [0 0 4]]


In [72]:
#indenty matrix
identity_matrix=np.eye(3)
# print(identity_matrix)

#np.eye (raw,column,k)
mat=np.eye(3,4,-1)
print(mat)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [120]:
indenty_m=np.eye(3,4,+2)
print(indenty_m)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


#ndarray Indexing and Slicing

In [129]:
print(arr1)

arr1[2]=100
print(arr1[2])

[  1   2 100   4   5]
100


In [138]:
print(arr2)
print(arr2[0][3])


[[1 2 3 4]
 [5 6 7 8]]
4


In [137]:
arr1_mod=arr1[1:4]
print(arr1_mod)

[  2 100   4]


2d array

In [147]:
#arr[raw_start:raw_end:step , column_start:column_end :step]
print(arr2)
#getting a raw

raw_f= arr2[0:1 , ]
raw_h=arr2[1:,]
print(raw_h)
print(raw_f)

[[1 2 3 4]
 [5 6 7 8]]
[[5 6 7 8]]
[[1 2 3 4]]


In [149]:
#geting a column
col_0=arr2[::,0:1]
print(col_0)
#geting a porsion
portion=arr2[::,0:2]
print(portion)

[[1]
 [5]]
[[1 2]
 [5 6]]


#Ndarray Copy Advanced Indexing and Iteration

In [158]:
arr1[2]=3
arr1_mod=arr1[1:4].copy()
arr1_mod[2]=200
print(arr1_mod)
print(arr1)

[  2   3 200]
[500   2   3   4   5]


advance indexing

In [172]:
lst=np.array([10,20,30,40])
values=lst[[1,3]]
print(values)


arr2[arr2>2]=0
print(arr2)

[20 40]
[[1 2 0 0]
 [0 0 0 0]]


In [170]:
print(arr2)
print(arr2[[0,1],[1,2]])

[[1 2 3 4]
 [5 6 7 8]]
[2 7]


In [178]:
arr=np.array([[10,20,30],[100,200,300]])

for i in np.nditer(arr3):
  print(i)

1
2
3
4
5
6
7
8
11
12
13
14
15
16
17
18
1
2
3
4
5
6
7
8
